# Generated by Django 5.1.2 on 2024-10-21 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdata_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
